//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squirrel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Squirrel.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorising.
        /// </summary>
        public static string LabelAuthorisingHeader {
            get {
                return ResourceManager.GetString("LabelAuthorisingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favourite.
        /// </summary>
        public static string LabelFavourite {
            get {
                return ResourceManager.GetString("LabelFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string LabelFavourites {
            get {
                return ResourceManager.GetString("LabelFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favourites have been added.
        /// </summary>
        public static string LabelNoFavouritesAdded {
            get {
                return ResourceManager.GetString("LabelNoFavouritesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone accent colour.
        /// </summary>
        public static string LabelPhoneAccentColour {
            get {
                return ResourceManager.GetString("LabelPhoneAccentColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squirrel accent colour (yellow).
        /// </summary>
        public static string LabelSquirrelAccentColour {
            get {
                return ResourceManager.GetString("LabelSquirrelAccentColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile colour.
        /// </summary>
        public static string LabelTileColour {
            get {
                return ResourceManager.GetString("LabelTileColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unfavourite.
        /// </summary>
        public static string LabelUnfavourite {
            get {
                return ResourceManager.GetString("LabelUnfavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding to favourites....
        /// </summary>
        public static string SysTrayAddingToFavourites {
            get {
                return ResourceManager.GetString("SysTrayAddingToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting favourites....
        /// </summary>
        public static string SysTrayGettingFavourites {
            get {
                return ResourceManager.GetString("SysTrayGettingFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing from favourites....
        /// </summary>
        public static string SysTrayRemovingFromFavourites {
            get {
                return ResourceManager.GetString("SysTrayRemovingFromFavourites", resourceCulture);
            }
        }
    }
}
